USE [master]

ALTER DATABASE [CorruptDemoDB]
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE [CorruptDemoDB] 
FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Backup\CorruptDemoDB.bak' 
WITH  FILE = 1,  NOUNLOAD,  STATS = 5, REPLACE

GO


