USE [master]
GO

CREATE SERVER AUDIT [Security Log]
TO SECURITY_LOG
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
)

CREATE SERVER AUDIT SPECIFICATION [Security]
FOR SERVER AUDIT [Security Log]
ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
ADD (DATABASE_PERMISSION_CHANGE_GROUP),
ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (SERVER_PERMISSION_CHANGE_GROUP),
ADD (LOGIN_CHANGE_PASSWORD_GROUP),
ADD (USER_CHANGE_PASSWORD_GROUP)
WITH (STATE = ON)
GO

ALTER SERVER AUDIT [Security Log] WITH (STATE = ON)
GO