	  select  'Alter', 'Attempt to change database structure is not allowed'
union select  'Begin','Begin of TSQL block inside dynamic T-SQL is not allowed'
union select  'Break', 'Usage of control flow inside dynamic SQL is not allowed'
union select  'Checkpoint', 'Attempt to control transaction behavior is not allowed'
union select  'Commit', 'Attempt to control transaction behavior is not allowed' 
union select  'Create', 'Attempt to change database structure is not allowed'
union select  'Cursor', 'Attempt to use cursors within Dynamic T-SQL execution is not allowed'
union select  'DBCC' ,'Using administrative Database consistency checker commands (DBCC) is not allowed'
union select  'Deny','Attempt to change any database permissions within Dynamic T-SQL not allowed'
union select  'Drop', 'Attempt to change database structure is not allowed'
union select  'Exec', 'Attempt to execute within Dynamic T-SQL not allowed'
union select  'Execute', 'Attempt to execute within Dynamic T-SQL not allowed'
union select  'Insert', 'Attempt to change the existing data within dynamic T-SQL Is not allowed'
union select  'Go', 'Attempt for multiple batch scripts within Dynamic T-SQL not allowed'
union select  'Grant', 'Attempt to change any database permissions within Dynamic T-SQL not allowed'
union select  'Opendatasource','Usage of distributed transaction row set function within Dynamic T-SQL not allowed'
union select  'Openquery', 'Usage of distributed transaction row set function within Dynamic T-SQL not allowed'
union select  'Openrowset', 'Usage of distributed transaction row set function within Dynamic T-SQL not allowed'
union select  'Shutdown', 'Attempt to control server behavior is strictly not allowed'
union select  'Sp_' ,'Any attempt to execute a system stored procedure within Dynamic T-SQL not allowed'
union select  'Tran', 'Attempt to control transaction behavior is not allowed'
union select  'Transaction', 'Attempt to control transaction behavior is not allowed'
union select  'Update' ,'Attempt to change the existing data within dynamic T-SQL is not allowed'
union select  'While', 'Usage of control flow inside dynamic SQL is not allowed'
union select  ';', 'Any attempt to concatenate T-SQL commands within a single T-SQL command is not allowed'
union select  '—', 'Entering comment marks inside with dynamic T-SQL command is a common SQL injection technique and is not allowed'
union select  'Xp_', 'Any attempt to execute an extended and/or system stored procedure within Dynamic T-SQL not allowed'
