Create Table ReservedWords
( id    int identity not null PRIMARY KEY, word  varchar(20))
go
Insert Into ReservedWords
values (' alter '),
       (' begin '),
(' break '),
(' checkpoint '),
(' commit '),
       (' create '),
(' cursor '),
       (' dbcc '),
(' deny '),
       (' drop '),
(' escape '),
(' exec '),
(' execute '),
       (' insert '),
       (' go '),
(' grant '),
(' opendatasource '),
(' openquery '),
(' openrowset '),
(' shutdown '),
       (' sp_'),
(' tran '),
(' transaction '),
(' update '),
(' while '),
       (' xp_'),
(';'),
       ('--')