ALTER TABLE DEVSMART2.FILTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVSMART2.FILTER CASCADE CONSTRAINTS;

CREATE TABLE DEVSMART2.FILTER
(
  FILTER_ID               NUMBER(10)            NOT NULL,
  FILTER_NAME             VARCHAR2(200 BYTE)    NOT NULL,
  FILTER_DESC             VARCHAR2(400 BYTE),
  ORGANIZATION_ID         NUMBER(10)            NOT NULL,
  PROCESS_GROUP_ID        NUMBER(10)            NOT NULL,
  TABLE_NAME              VARCHAR2(40 BYTE)     NOT NULL,
  COLUMN_NAME             VARCHAR2(40 BYTE)     NOT NULL,
  OPERATION_NUM           NUMBER(2)             NOT NULL,
  OPERATION_NEGATION_FLG  NUMBER(1)             DEFAULT 0                     NOT NULL,
  INCLUDE_FLG             NUMBER(1)             DEFAULT 1                     NOT NULL,
  DATA_TYPE_NAME          VARCHAR2(20 BYTE)     NOT NULL,
  VALUE_NUM               NUMBER(16,4),
  HIGH_VALUE_NUM          NUMBER(16,4),
  VALUE_TEXT              VARCHAR2(40 BYTE),
  HIGH_VALUE_TEXT         VARCHAR2(40 BYTE),
  VALUE_DT                DATE,
  HIGH_VALUE_DT           DATE,
  CREATE_ENDUSER_ID       NUMBER(10)            NOT NULL,
  CREATE_DT               TIMESTAMP(6)          DEFAULT SYSTIMESTAMP          NOT NULL,
  UPDATE_ENDUSER_ID       NUMBER(10),
  UPDATE_DT               TIMESTAMP(6),
  FILTER_VER_NUM          NUMBER(4)             DEFAULT 1                     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DEVSMART2.FILTER_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVSMART2.FILTER_GROUP CASCADE CONSTRAINTS;

CREATE TABLE DEVSMART2.FILTER_GROUP
(
  FILTER_GROUP_ID       NUMBER(10)              NOT NULL,
  FILTER_GROUP_NAME     VARCHAR2(80 BYTE)       NOT NULL,
  FILTER_GROUP_DESC     VARCHAR2(400 BYTE),
  ORGANIZATION_ID       NUMBER(10)              NOT NULL,
  PROCESS_GROUP_ID      NUMBER(10)              NOT NULL,
  CREATE_ENDUSER_ID     NUMBER(10)              NOT NULL,
  CREATE_DT             TIMESTAMP(6)            DEFAULT SYSTIMESTAMP          NOT NULL,
  UPDATE_ENDUSER_ID     NUMBER(10),
  UPDATE_DT             TIMESTAMP(6),
  FILTER_GROUP_VER_NUM  NUMBER(4)               DEFAULT 1                     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DEVSMART2.FILTER_GROUP_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVSMART2.FILTER_GROUP_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE DEVSMART2.FILTER_GROUP_DETAIL
(
  FILTER_GROUP_ID              NUMBER(10)       NOT NULL,
  FILTER_ID                    NUMBER(10)       NOT NULL,
  CREATE_ENDUSER_ID            NUMBER(10)       NOT NULL,
  CREATE_DT                    TIMESTAMP(6)     DEFAULT SYSTIMESTAMP          NOT NULL,
  UPDATE_ENDUSER_ID            NUMBER(10),
  UPDATE_DT                    TIMESTAMP(6),
  FILTER_GROUP_DETAIL_VER_NUM  NUMBER(4)        DEFAULT 1                     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEVSMART2.FILTER_GROUP_DETAIL_PK ON DEVSMART2.FILTER_GROUP_DETAIL
(FILTER_GROUP_ID, FILTER_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEVSMART2.FILTER_GROUP_IX01 ON DEVSMART2.FILTER_GROUP
(ORGANIZATION_ID, PROCESS_GROUP_ID, FILTER_GROUP_NAME)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVSMART2.FILTER_GROUP_PK ON DEVSMART2.FILTER_GROUP
(FILTER_GROUP_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEVSMART2.FILTER_IX01 ON DEVSMART2.FILTER
(ORGANIZATION_ID, PROCESS_GROUP_ID, FILTER_NAME)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEVSMART2.FILTER_IX02 ON DEVSMART2.FILTER
(ORGANIZATION_ID, PROCESS_GROUP_ID, TABLE_NAME, COLUMN_NAME)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVSMART2.FILTER_PK ON DEVSMART2.FILTER
(FILTER_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE DEVSMART2.FILTER ADD (
  CONSTRAINT FILTER_PK
  PRIMARY KEY
  (FILTER_ID)
  USING INDEX DEVSMART2.FILTER_PK);

ALTER TABLE DEVSMART2.FILTER_GROUP ADD (
  CONSTRAINT FILTER_GROUP_PK
  PRIMARY KEY
  (FILTER_GROUP_ID)
  USING INDEX DEVSMART2.FILTER_GROUP_PK);

ALTER TABLE DEVSMART2.FILTER_GROUP_DETAIL ADD (
  CONSTRAINT FILTER_GROUP_DETAIL_PK
  PRIMARY KEY
  (FILTER_GROUP_ID, FILTER_ID)
  USING INDEX DEVSMART2.FILTER_GROUP_DETAIL_PK);

ALTER TABLE DEVSMART2.FILTER ADD (
  CONSTRAINT REFALLOWABLE_FILTER47 
  FOREIGN KEY (PROCESS_GROUP_ID, TABLE_NAME, COLUMN_NAME) 
  REFERENCES DEVSMART2.ALLOWABLE_FILTER (PROCESS_GROUP_ID,TABLE_NAME,COLUMN_NAME),
  CONSTRAINT REFOPERATION25 
  FOREIGN KEY (OPERATION_NUM) 
  REFERENCES DEVSMART2.OPERATION (OPERATION_NUM),
  CONSTRAINT REFORG_PROCESS_GROUP20 
  FOREIGN KEY (ORGANIZATION_ID, PROCESS_GROUP_ID) 
  REFERENCES DEVSMART2.ORG_PROCESS_GROUP (ORGANIZATION_ID,PROCESS_GROUP_ID));

ALTER TABLE DEVSMART2.FILTER_GROUP ADD (
  CONSTRAINT REFORG_PROCESS_GROUP21 
  FOREIGN KEY (ORGANIZATION_ID, PROCESS_GROUP_ID) 
  REFERENCES DEVSMART2.ORG_PROCESS_GROUP (ORGANIZATION_ID,PROCESS_GROUP_ID));

ALTER TABLE DEVSMART2.FILTER_GROUP_DETAIL ADD (
  CONSTRAINT REFFILTER23 
  FOREIGN KEY (FILTER_ID) 
  REFERENCES DEVSMART2.FILTER (FILTER_ID),
  CONSTRAINT REFFILTER_GROUP22 
  FOREIGN KEY (FILTER_GROUP_ID) 
  REFERENCES DEVSMART2.FILTER_GROUP (FILTER_GROUP_ID));
