



USE [master]
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev', SIZE = 8192000KB)
GO
ALTER DATABASE [tempdb]MODIFY FILE ( NAME = N'tempdev1', FILENAME = N'P:\SQLTempDB\SQL03\tempdev1.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev2', FILENAME = N'P:\SQLTempDB\SQL03\tempdev2.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev3', FILENAME = N'P:\SQLTempDB\SQL03\tempdev3.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev4', FILENAME = N'P:\SQLTempDB\SQL03\tempdev4.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev5', FILENAME = N'P:\SQLTempDB\SQL03\tempdev5.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev6', FILENAME = N'P:\SQLTempDB\SQL03\tempdev6.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev7', FILENAME = N'P:\SQLTempDB\SQL03\tempdev7.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev8', FILENAME = N'P:\SQLTempDB\SQL03\tempdev8.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev9', FILENAME = N'P:\SQLTempDB\SQL03\tempdev9.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev10', FILENAME = N'P:\SQLTempDB\SQL03\tempdev10.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev11', FILENAME = N'P:\SQLTempDB\SQL03\tempdev11.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev12', FILENAME = N'P:\SQLTempDB\SQL03\tempdev12.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev13', FILENAME = N'P:\SQLTempDB\SQL03\tempdev13.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev14', FILENAME = N'P:\SQLTempDB\SQL03\tempdev14.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev15', FILENAME = N'P:\SQLTempDB\SQL03\tempdev15.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev16', FILENAME = N'P:\SQLTempDB\SQL03\tempdev16.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev17', FILENAME = N'P:\SQLTempDB\SQL03\tempdev17.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev18', FILENAME = N'P:\SQLTempDB\SQL03\tempdev18.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev19', FILENAME = N'P:\SQLTempDB\SQL03\tempdev19.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev20', FILENAME = N'P:\SQLTempDB\SQL03\tempdev20.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev21', FILENAME = N'P:\SQLTempDB\SQL03\tempdev21.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev22', FILENAME = N'P:\SQLTempDB\SQL03\tempdev22.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev23', FILENAME = N'P:\SQLTempDB\SQL03\tempdev23.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev24', FILENAME = N'P:\SQLTempDB\SQL03\tempdev24.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev25', FILENAME = N'P:\SQLTempDB\SQL03\tempdev25.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev26', FILENAME = N'P:\SQLTempDB\SQL03\tempdev26.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev27', FILENAME = N'P:\SQLTempDB\SQL03\tempdev27.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev28', FILENAME = N'P:\SQLTempDB\SQL03\tempdev28.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev29', FILENAME = N'P:\SQLTempDB\SQL03\tempdev29.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev30', FILENAME = N'P:\SQLTempDB\SQL03\tempdev30.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdev31', FILENAME = N'P:\SQLTempDB\SQL03\tempdev31.ndf' , SIZE = 8192000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'templog', SIZE = 8192000KB )
GO