
ALTER DATABASE CorruptDemoDB
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;


ALTER DATABASE CorruptDemoDB
SET OFFLINE;


ALTER DATABASE CorruptDemoDB
SET ONLINE;

ALTER DATABASE CorruptDemoDB
SET MULTI_USER;



ALTER DATABASE CorruptDemoDB
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DBCC CHECKDB(CorruptDemoDB,REPAIR_ALLOW_DATA_LOSS) 

USE CorruptDemoDB;

SELECT * FROM corruptData;