IF DB_ID('AGDB01') IS NOT NULL
	DROP DATABASE AGDB01;
GO
CREATE DATABASE AGDB01;
GO
IF DB_ID('AGDB02') IS NOT NULL
	DROP DATABASE AGDB02;
GO
CREATE DATABASE AGDB02;
GO

CREATE TABLE AGDB01.dbo.T1 (F1 int not null PRIMARY KEY);
GO
INSERT	AGDB01.dbo.T1
VALUES	(1), (2), (3), (4), (5);
GO
CREATE TABLE AGDB02.dbo.T2 (F1 int not null PRIMARY KEY);
GO
INSERT	AGDB02.dbo.T2
VALUES	(1), (2), (3), (4), (5);
GO