IF OBJECT_ID('$(BIS_SECURITY_SCHEMA).trg_IUD_ORGANIZATION_AUDIT') IS NOT NULL
   DROP TRIGGER $(BIS_SECURITY_SCHEMA).trg_IUD_ORGANIZATION_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'$(BIS_SECURITY_SCHEMA)' and table_name = N'vw_ORGANIZATION_AUDIT')
   BEGIN
      DROP VIEW $(BIS_SECURITY_SCHEMA).vw_ORGANIZATION_AUDIT;
      PRINT 'VIEW $(BIS_SECURITY_SCHEMA).vw_ORGANIZATION_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('$(BIS_SECURITY_SCHEMA).trg_IUD_SECURED_USER_AUDIT') IS NOT NULL
   DROP TRIGGER $(BIS_SECURITY_SCHEMA).trg_IUD_SECURED_USER_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'$(BIS_SECURITY_SCHEMA)' and table_name = N'vw_SECURED_USER_AUDIT')
   BEGIN
      DROP VIEW $(BIS_SECURITY_SCHEMA).vw_SECURED_USER_AUDIT;
      PRINT 'VIEW $(BIS_SECURITY_SCHEMA).vw_SECURED_USER_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('$(BIS_SECURITY_SCHEMA).trg_IUD_USER_RULE_AUDIT') IS NOT NULL
   DROP TRIGGER $(BIS_SECURITY_SCHEMA).trg_IUD_USER_RULE_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'$(BIS_SECURITY_SCHEMA)' and table_name = N'vw_USER_RULE_AUDIT')
   BEGIN
      DROP VIEW $(BIS_SECURITY_SCHEMA).vw_USER_RULE_AUDIT;
      PRINT 'VIEW $(BIS_SECURITY_SCHEMA).vw_USER_RULE_AUDIT has been dropped.';
   END;
GO

