#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 0006e28e-7860-4cc3-bf13-b70155d906b4
# Source File: test1.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
0wcAAB+LCAAAAAAABAC9VV1r2zAUfR/sPwg9m9iO46YFW7B6K4yVrSxZu7ciy9edFlkKkpzW+/WT
PxLapl2y0gaDkaxzde6590hOvgNTK9DNR2opcgPDlUzxGJP37xBKvml+wyUVZ1zAV1oBsWBsOFqa
MvG31vqI/Dcwi2yzhBTPGmOhGl1xWahbMzpTuurfHnpqyUOXQwKTUdA+HspqYWsNqYTaaio8dFHn
grMv0MzVAmSaT6c0ZvFReBJNIDg+wUi6VFJcuv1CjNgvLgrtcDhT0molTC/MJXqh1RK0bYaATHCQ
dsb/ACaTqWOOouPEX4OeCWplY9Jx7cTO4c5i0urchn5aOe4Bd65oMex53Y4Tv1tdQ3fX97S2Vsk3
r3De0fyzxttFOFeMWkePSXgUeSgcb9f4uSoPfHvg+yZOYw+Noz3gc5p/lgXcYRLsg+7auH8yPwxc
clNTMbONgFPKFpkSSmMy1zU8FX/fC86UbLFhu+6mj/zg94boD9+DyQdjoHKtBLPGDl8aUhmmtOD5
K9gh8Te7PmbpDXgIjlc3+W7G9r48DJGmt1zevIQriMq4nJZhWMQBjehurp+VOIwmrp1NlW5moFec
wYta9t/qMqXhIPIGVe5sO2lvoG0z7c924t//iZO/0pdoqtMHAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.93
     Generated on:       11/11/2015 9:49 AM
     Generated by:       BryanCafferky
     Organization:       BPC Global Solutions LLC
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2015
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-test1_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$button1 = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$button1_Click={
		#TODO: Place custom script here
		$button1.Text = 'Pressed'
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$button1.remove_Click($button1_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($button1)
	$form1.ClientSize = '470, 338'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# button1
	#
	$button1.Location = '163, 128'
	$button1.Name = 'button1'
	$button1.Size = '75, 23'
	$button1.TabIndex = 0
	$button1.Text = 'button1'
	$button1.UseVisualStyleBackColor = $True
	$button1.add_Click($button1_Click)
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Call-test1_psf | Out-Null
