DECLARE @SQL VARCHAR(8000),
@SCHNAME VARCHAR(30),
@TABLENAME VARCHAR(60),
@COLUMNNAME VARCHAR(60),
@SEARCHSTRING VARCHAR(50)

SET @SEARCHSTRING = 'AG'

IF OBJECT_ID('TEMPDB..#Results') IS NOT NULL
    DROP TABLE #Results

CREATE TABLE #RESULTS(SCHNAME VARCHAR(30),TBLNAME VARCHAR(60),COLNAME VARCHAR(60),SQL VARCHAR(600))


IF OBJECT_ID('TEMPDB..#FKFINDER') IS NOT NULL
    DROP TABLE #FKFINDER

SELECT SYS.SCHEMAS.NAME AS SCHNAME,
		SYS.OBJECTS.NAME AS TBLNAME,
		SYS.COLUMNS.NAME AS COLNAME,
		SYS.TYPES.NAME AS DATATYPE
INTO #FKFINDER
FROM SYS.OBJECTS
INNER JOIN SYS.COLUMNS ON SYS.OBJECTS.object_id=SYS.COLUMNS.object_id
INNER JOIN SYS.TYPES ON SYS.COLUMNS.user_type_id = SYS.TYPES.user_type_id
INNER JOIN SYS.SCHEMAS ON SYS.SCHEMAS.schema_id = SYS.OBJECTS.schema_id
WHERE SYS.OBJECTS.TYPE='U'
AND SYS.TYPES.name IN ('VARCHAR','NVARCHAR','CHAR','NCHAR')
ORDER BY SCHNAME,TBLNAME,COLNAME

	DECLARE C1 CURSOR FOR 
	SELECT SCHNAME,TBLNAME,COLNAME FROM #FKFINDER ORDER BY SCHNAME,TBLNAME,COLNAME
		OPEN C1
			FETCH NEXT FROM C1 INTO @SCHNAME,@TABLENAME,@COLUMNNAME
				WHILE @@FETCH_STATUS <> -1
				BEGIN
				SET @SQL = 'IF EXISTS(SELECT 1 FROM ' + @SCHNAME + '.' + @TABLENAME + ' WHERE ' + @COLUMNNAME + ' LIKE ''%' + @SEARCHSTRING + '%'') INSERT INTO #RESULTS(SCHNAME,TBLNAME,COLNAME,SQL) VALUES(''' + @SCHNAME + ''',''' + @TABLENAME + ''',''' + @COLUMNNAME + ''','' SELECT '''''+ @TABLENAME + ''''' AS TableName,'''''+ @COLUMNNAME + ''''' AS ColumnName, ''''SELECT * FROM ' + @SCHNAME + '.' + @TABLENAME + ' WHERE ' + @COLUMNNAME + ' LIKE ''''' + @SEARCHSTRING + ''''' '') ;'
				PRINT @SQL
				EXEC (@SQL)
				FETCH NEXT FROM C1 INTO @SCHNAME,@TABLENAME,@COLUMNNAME
				END
		CLOSE C1
	DEALLOCATE C1

SELECT * FROM #RESULTS

DROP TABLE #RESULTS
DROP TABLE #FKFINDER
