/****** Object: Database [InstallPoint]   Script Date: 1/16/2013 8:46:27 AM ******/
USE [master];
GO

DROP DATABASE [InstallPoint]
GO

CREATE DATABASE [InstallPoint]
ON
PRIMARY
( NAME = N'InstallPoint', FILENAME = N'D:\MSSQLData\InstallPoint.mdf', SIZE = 5MB, FILEGROWTH = 1MB )
LOG ON
( NAME = N'InstallPoint_log', FILENAME = N'D:\MSSQLData\InstallPoint_log.ldf', SIZE = 5MB, MAXSIZE = 2097152 MB, FILEGROWTH = 10% )
COLLATE SQL_Latin1_General_CP1_CI_AS;
GO
USE [InstallPoint];
GO
ALTER DATABASE [InstallPoint] SET COMPATIBILITY_LEVEL = 110;
GO
ALTER DATABASE [InstallPoint] SET ANSI_NULL_DEFAULT OFF;
GO
ALTER DATABASE [InstallPoint] SET ANSI_NULLS OFF;
GO
ALTER DATABASE [InstallPoint] SET ANSI_PADDING OFF;
GO
ALTER DATABASE [InstallPoint] SET ANSI_WARNINGS OFF;
GO
ALTER DATABASE [InstallPoint] SET ARITHABORT OFF;
GO
ALTER DATABASE [InstallPoint] SET AUTO_CLOSE OFF;
GO
ALTER DATABASE [InstallPoint] SET AUTO_CREATE_STATISTICS ON;
GO
ALTER DATABASE [InstallPoint] SET AUTO_SHRINK OFF;
GO
ALTER DATABASE [InstallPoint] SET AUTO_UPDATE_STATISTICS ON;
GO
ALTER DATABASE [InstallPoint] SET CURSOR_CLOSE_ON_COMMIT OFF;
GO
ALTER DATABASE [InstallPoint] SET CURSOR_DEFAULT GLOBAL;
GO
ALTER DATABASE [InstallPoint] SET CONCAT_NULL_YIELDS_NULL OFF;
GO
ALTER DATABASE [InstallPoint] SET NUMERIC_ROUNDABORT OFF;
GO
ALTER DATABASE [InstallPoint] SET QUOTED_IDENTIFIER OFF;
GO
ALTER DATABASE [InstallPoint] SET RECURSIVE_TRIGGERS OFF;
GO
ALTER DATABASE [InstallPoint] SET DISABLE_BROKER;
GO
ALTER DATABASE [InstallPoint] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
GO
ALTER DATABASE [InstallPoint] SET DATE_CORRELATION_OPTIMIZATION OFF;
GO
ALTER DATABASE [InstallPoint] SET TRUSTWORTHY OFF;
GO
ALTER DATABASE [InstallPoint] SET ALLOW_SNAPSHOT_ISOLATION OFF;
GO
ALTER DATABASE [InstallPoint] SET READ_COMMITTED_SNAPSHOT OFF;
GO
ALTER DATABASE [InstallPoint] SET PARAMETERIZATION SIMPLE;
GO
ALTER DATABASE [InstallPoint] SET RECOVERY FULL;
GO
ALTER DATABASE [InstallPoint] SET MULTI_USER;
GO
ALTER DATABASE [InstallPoint] SET PAGE_VERIFY CHECKSUM;
GO
ALTER DATABASE [InstallPoint] SET DB_CHAINING OFF;
GO
ALTER DATABASE [InstallPoint] SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF);
GO
EXEC sys.sp_changedbowner @loginame = N'SEI-DOMAIN-1\POBrien', @map = false;
GO
USE master;
GO
USE [InstallPoint];
GO
