IF OBJECT_ID('dbo.trg_IUD_ADDRESS_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_ADDRESS_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_ADDRESS_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_ADDRESS_AUDIT;
      PRINT 'VIEW dbo.vw_ADDRESS_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_ALLOWABLE_PARAMETER_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_ALLOWABLE_PARAMETER_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_ALLOWABLE_PARAMETER_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_ALLOWABLE_PARAMETER_AUDIT;
      PRINT 'VIEW dbo.vw_ALLOWABLE_PARAMETER_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_COMPONENT_PARAMETER_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_COMPONENT_PARAMETER_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_COMPONENT_PARAMETER_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_COMPONENT_PARAMETER_AUDIT;
      PRINT 'VIEW dbo.vw_COMPONENT_PARAMETER_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_CONTACT_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_CONTACT_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_CONTACT_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_CONTACT_AUDIT;
      PRINT 'VIEW dbo.vw_CONTACT_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_CREDENTIAL_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_CREDENTIAL_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_CREDENTIAL_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_CREDENTIAL_AUDIT;
      PRINT 'VIEW dbo.vw_CREDENTIAL_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_GENERATE_NAME_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_GENERATE_NAME_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_GENERATE_NAME_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_GENERATE_NAME_AUDIT;
      PRINT 'VIEW dbo.vw_GENERATE_NAME_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_INSTALL_USER_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_INSTALL_USER_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_INSTALL_USER_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_INSTALL_USER_AUDIT;
      PRINT 'VIEW dbo.vw_INSTALL_USER_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_JOB_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_JOB_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_JOB_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_JOB_AUDIT;
      PRINT 'VIEW dbo.vw_JOB_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_ORGANIZATION_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_ORGANIZATION_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_ORGANIZATION_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_ORGANIZATION_AUDIT;
      PRINT 'VIEW dbo.vw_ORGANIZATION_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PARAMETER_USAGE_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PARAMETER_USAGE_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PARAMETER_USAGE_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PARAMETER_USAGE_AUDIT;
      PRINT 'VIEW dbo.vw_PARAMETER_USAGE_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PARM_DOMAIN_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PARM_DOMAIN_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PARM_DOMAIN_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PARM_DOMAIN_AUDIT;
      PRINT 'VIEW dbo.vw_PARM_DOMAIN_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PEOPLE_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PEOPLE_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PEOPLE_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PEOPLE_AUDIT;
      PRINT 'VIEW dbo.vw_PEOPLE_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PRODUCT_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PRODUCT_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PRODUCT_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PRODUCT_AUDIT;
      PRINT 'VIEW dbo.vw_PRODUCT_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PRODUCT_COMPATIBLE_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PRODUCT_COMPATIBLE_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PRODUCT_COMPATIBLE_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PRODUCT_COMPATIBLE_AUDIT;
      PRINT 'VIEW dbo.vw_PRODUCT_COMPATIBLE_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PRODUCT_COMPONENT_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PRODUCT_COMPONENT_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PRODUCT_COMPONENT_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PRODUCT_COMPONENT_AUDIT;
      PRINT 'VIEW dbo.vw_PRODUCT_COMPONENT_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PRODUCT_ELIGIBILITY_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PRODUCT_ELIGIBILITY_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PRODUCT_ELIGIBILITY_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PRODUCT_ELIGIBILITY_AUDIT;
      PRINT 'VIEW dbo.vw_PRODUCT_ELIGIBILITY_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PRODUCT_INSTALLATION_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PRODUCT_INSTALLATION_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PRODUCT_INSTALLATION_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PRODUCT_INSTALLATION_AUDIT;
      PRINT 'VIEW dbo.vw_PRODUCT_INSTALLATION_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_PRODUCT_VERSION_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_PRODUCT_VERSION_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_PRODUCT_VERSION_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_PRODUCT_VERSION_AUDIT;
      PRINT 'VIEW dbo.vw_PRODUCT_VERSION_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_RELATED_SERVER_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_RELATED_SERVER_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_RELATED_SERVER_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_RELATED_SERVER_AUDIT;
      PRINT 'VIEW dbo.vw_RELATED_SERVER_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_SCHEDULE_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_SCHEDULE_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_SCHEDULE_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_SCHEDULE_AUDIT;
      PRINT 'VIEW dbo.vw_SCHEDULE_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_SCHEDULE_DETAIL_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_SCHEDULE_DETAIL_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_SCHEDULE_DETAIL_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_SCHEDULE_DETAIL_AUDIT;
      PRINT 'VIEW dbo.vw_SCHEDULE_DETAIL_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_SERVER_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_SERVER_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_SERVER_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_SERVER_AUDIT;
      PRINT 'VIEW dbo.vw_SERVER_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_TASK_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_TASK_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_TASK_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_TASK_AUDIT;
      PRINT 'VIEW dbo.vw_TASK_AUDIT has been dropped.';
   END;
GO

IF OBJECT_ID('dbo.trg_IUD_TASK_INSTANCE_AUDIT') IS NOT NULL
   DROP TRIGGER dbo.trg_IUD_TASK_INSTANCE_AUDIT
GO

IF EXISTS
   (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
    WHERE table_schema = N'dbo' and table_name = N'vw_TASK_INSTANCE_AUDIT')
   BEGIN
      DROP VIEW dbo.vw_TASK_INSTANCE_AUDIT;
      PRINT 'VIEW dbo.vw_TASK_INSTANCE_AUDIT has been dropped.';
   END;
GO

