--   Project: BIS Account Restriction Facility (BARF)

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'Audit_Trail')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).Audit_Trail;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).Audit_Trail >>>';
  END;
GO

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'DB_Control')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).DB_Control;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).DB_Control >>>';
  END;
GO

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'DB_Control_History')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).DB_Control_History;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).DB_Control_History >>>';
  END;
GO

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'USER_RULE')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).USER_RULE;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).USER_RULE >>>';
  END;
GO

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'QUALIFICATION_COLUMN')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).QUALIFICATION_COLUMN;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).QUALIFICATION_COLUMN >>>';
  END;
GO

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'SECURED_USER')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).SECURED_USER;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).SECURED_USER >>>';
  END;
GO

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'ORGANIZATION')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).ORGANIZATION;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).ORGANIZATION >>>';
  END;
GO

IF EXISTS
     (SELECT *
      FROM   INFORMATION_SCHEMA.TABLES
      WHERE  table_schema = N'$(BIS_SECURITY_SCHEMA)' AND table_name = N'Secured_User_Type')
  BEGIN
   DROP TABLE $(BIS_SECURITY_SCHEMA).Secured_User_Type;
    PRINT '<<< DROPPED TABLE $(BIS_SECURITY_SCHEMA).Secured_User_Type >>>';
  END;
GO