SELECT 'INSERT INTO fld_in_qry' + 
 '(' + 
 '[INQ_NUM],' + 
 '[QRY_NUM],' + 
 '[ENTITY_NUM],' + 
 '[FLD_NUM],' + 
 '[SEQ_NUM],' + 
 '[INTERNL_NME],' + 
 '[FLD_BUS_NME],' + 
 '[NLS_CDE],' + 
 '[DATA_CLS_NUM],' + 
 '[DATA_TYP_NUM],' + 
 '[GRID_ALIGN_NUM],' + 
 '[GRID_WIDTH_NUM],' + 
 '[FORMAT_OPT_NUM],' + 
 '[FORMAT_TXT],' + 
 '[TOTAL_OPT_NUM],' + 
 '[INDENT_BY],' + 
 '[INDENT_BY_AMT],' + 
 '[FILTER_SUPPRESS_IND],' + 
 '[FORMULA_ID],' + 
 '[GROUP_BY_IND],' + 
 '[SCALE],' + 
 '[TOTAL_BY],' + 
 '[INCL_GRAND],' + 
 '[SORT_OPT],' + 
 '[BREAK_SUBTOTAL],' + 
 '[VALUE_COL],' + 
 '[DUPS],' + 
 '[LST_CHG_USR_ID],' + 
 '[LST_CHG_TMS],' + 
 '[HIDE_IND],' + 
 '[GRPVAL_IN_SUBTOTAL_IND],' + 
 '[REQD_IND],' + 
 '[DATA_CALC_IND],' + 
 '[Hide_Label_IND],' + 
 '[Chart_Value]' +
 ')' + 
 ' VALUES (' +
 CASE WHEN [INQ_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [INQ_NUM]) END + ', ' +
 CASE WHEN [QRY_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [QRY_NUM]) END + ', ' +
 CASE WHEN [ENTITY_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [ENTITY_NUM]) END + ', ' +
 CASE WHEN [FLD_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [FLD_NUM]) END + ', ' +
 CASE WHEN [SEQ_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [SEQ_NUM]) END + ', ' +
 CASE WHEN [INTERNL_NME] IS NULL THEN 'NULL' ELSE '''' + REPLACE([INTERNL_NME], '''', '''''') + '''' END + ', ' +
 CASE WHEN [FLD_BUS_NME] IS NULL THEN 'NULL' ELSE '''' + REPLACE([FLD_BUS_NME], '''', '''''') + '''' END + ', ' +
 CASE WHEN [NLS_CDE] IS NULL THEN 'NULL' ELSE '''' + REPLACE([NLS_CDE], '''', '''''') + '''' END + ', ' +
 CASE WHEN [DATA_CLS_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [DATA_CLS_NUM]) END + ', ' +
 CASE WHEN [DATA_TYP_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [DATA_TYP_NUM]) END + ', ' +
 CASE WHEN [GRID_ALIGN_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [GRID_ALIGN_NUM]) END + ', ' +
 CASE WHEN [GRID_WIDTH_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [GRID_WIDTH_NUM]) END + ', ' +
 CASE WHEN [FORMAT_OPT_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [FORMAT_OPT_NUM]) END + ', ' +
 CASE WHEN [FORMAT_TXT] IS NULL THEN 'NULL' ELSE '''' + REPLACE([FORMAT_TXT], '''', '''''') + '''' END + ', ' +
 CASE WHEN [TOTAL_OPT_NUM] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [TOTAL_OPT_NUM]) END + ', ' +
 CASE WHEN [INDENT_BY] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [INDENT_BY]) END + ', ' +
 CASE WHEN [INDENT_BY_AMT] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [INDENT_BY_AMT]) END + ', ' +
 CASE WHEN [FILTER_SUPPRESS_IND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [FILTER_SUPPRESS_IND]) END + ', ' +
 CASE WHEN [FORMULA_ID] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [FORMULA_ID]) END + ', ' +
 CASE WHEN [GROUP_BY_IND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [GROUP_BY_IND]) END + ', ' +
 CASE WHEN [SCALE] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [SCALE]) END + ', ' +
 CASE WHEN [TOTAL_BY] IS NULL THEN 'NULL' ELSE '''' + REPLACE([TOTAL_BY], '''', '''''') + '''' END + ', ' +
 CASE WHEN [INCL_GRAND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [INCL_GRAND]) END + ', ' +
 CASE WHEN [SORT_OPT] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [SORT_OPT]) END + ', ' +
 CASE WHEN [BREAK_SUBTOTAL] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [BREAK_SUBTOTAL]) END + ', ' +
 CASE WHEN [VALUE_COL] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [VALUE_COL]) END + ', ' +
 CASE WHEN [DUPS] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [DUPS]) END + ', ' +
 CASE WHEN [LST_CHG_USR_ID] IS NULL THEN 'NULL' ELSE '''' + REPLACE([LST_CHG_USR_ID], '''', '''''') + '''' END + ', ' +
 CASE WHEN [LST_CHG_TMS] IS NULL THEN 'NULL' ELSE 'CONVERT(DATETIME, ' + master.sys.fn_varbintohexstr (CONVERT(BINARY(8), [LST_CHG_TMS])) + ')' END + ', ' +
 CASE WHEN [HIDE_IND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [HIDE_IND]) END + ', ' +
 CASE WHEN [GRPVAL_IN_SUBTOTAL_IND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [GRPVAL_IN_SUBTOTAL_IND]) END + ', ' +
 CASE WHEN [REQD_IND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [REQD_IND]) END + ', ' +
 CASE WHEN [DATA_CALC_IND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [DATA_CALC_IND]) END + ', ' +
 CASE WHEN [Hide_Label_IND] IS NULL THEN 'NULL' ELSE CONVERT(VARCHAR(40), [Hide_Label_IND]) END + ', ' +
 CASE WHEN [Chart_Value] IS NULL THEN 'NULL' ELSE '''' + REPLACE([Chart_Value], '''', '''''') + '''' END + 
 ')'
 FROM fld_in_qry
where inq_num = 15946
and entity_num = 10622
and fld_num = 1001