DECLARE @inq_num INT

SET @inq_num = 14756

SELECT *
FROM FLD_IN_QRY
WHERE FLD_IN_QRY.INQ_NUM = @inq_num

SELECT *
FROM INQ_IN_FOLDER
WHERE INQ_IN_FOLDER.INQ_NUM = @inq_num

SELECT *
FROM FILTER f
WHERE f.FILTER_NUM IN (
		SELECT FILTER_NUM
		FROM QRY_DEF
		WHERE INQ_NUM = @inq_num
		)

SELECT *
FROM QRY_DEF q
WHERE q.INQ_NUM = @inq_num

SELECT *
FROM QUERY_PARAM_DEF
WHERE DEF_TYP = 'I'
	AND TYP_IND = 'S'
	AND TYP_QRY_RPT_NUM = @inq_num

SELECT *
FROM DW_FUNCTION_ITEM
WHERE DW_FUNCTION_ITEM.INQ_NUM = @inq_num

SELECT *
FROM DASHBOARD_CONTENT
WHERE DASHBOARD_CONTENT.INQ_NUM = @inq_num

SELECT *
FROM DW_TASK
WHERE DW_TASK.INQ_NUM = @inq_num

SELECT *
FROM DW_INQRUNVAL_DEF
WHERE DW_INQRUNVAL_DEF.INQ_NUM = @inq_num

SELECT *
FROM DW_CHT_DEF C
WHERE C.INQ_NUM = @inq_num

SELECT *
FROM DW_FLD_IN_CHT C
WHERE C.INQ_NUM = @inq_num
