USE [master]
GO

/****** Object:  Database [DBA_DataCollector]    Script Date: 12/31/2014 9:44:30 PM ******/
CREATE DATABASE [DBA_DataCollector]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WDBS_DataCollector', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\Template Data\DBA_DataCollector.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WDBS_DataCollector_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\Template Data\DBA_DataCollector_log.ldf' , SIZE = 29696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBA_DataCollector] ADD FILEGROUP [Index]
GO

ALTER DATABASE [DBA_DataCollector] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBA_DataCollector].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBA_DataCollector] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DBA_DataCollector] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBA_DataCollector] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBA_DataCollector] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBA_DataCollector] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBA_DataCollector] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET RECOVERY FULL 
GO

ALTER DATABASE [DBA_DataCollector] SET  MULTI_USER 
GO

ALTER DATABASE [DBA_DataCollector] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBA_DataCollector] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBA_DataCollector] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBA_DataCollector] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBA_DataCollector] SET  READ_WRITE 
GO


